import streamlit as st
import uuid as uuid_lib
from typing import List, Dict, Any, Optional
from datetime import datetime, timezone
from langgraph.store.memory import InMemoryStore
from pydc.llm.llm_loader import get_langchain_embeddings
from pydc.util.constants import (
    MEMORY_STORE_KEY,
    MEMORY_TYPE_DATASET_SUMMARY, MEMORY_TYPE_PRIOR_PROMPT, 
    MEMORY_KEY, MEMORY_TS,
    AGENT_CODE, USER_PROMPT
)  

log = st.logger.get_logger(__name__)

def _get_store() -> InMemoryStore:
    """Gets or initializes the InMemoryStore for this Streamlit session."""
    if MEMORY_STORE_KEY not in st.session_state:
        st.session_state.memory_store = InMemoryStore(
            index={
                "embed": get_langchain_embeddings(),
                "dims": 768,  # nomic-embed-text dimensionality
                "fields": [MEMORY_KEY], # embed MEMORY_KEY field of value dict
            }
        )
    return st.session_state.memory_store

def _get_namespace() -> tuple:
    """Returns a unique namespace for the current user session."""
    if "session_id" not in st.session_state:
        st.session_state.session_id = str(uuid_lib.uuid4())
    return ("session", st.session_state.session_id, "memories")


def _get_timestamp() -> str:
    # Get current time in UTC
    now_utc = datetime.now(timezone.utc)
    fmt_dt = now_utc.strftime("%Y-%m-%dT%H:%M:%SZ")
    return fmt_dt
    
def store_dataset_summary(schema: dict, columns: list, file_name: str) -> None:
    """
    Stores a summary of the uploaded dataset in the memory store.
    
    Args:
        schema: Dictionary mapping column names to data types.
        columns: List of column names.
        file_name: Name of the uploaded file.
    """
    store = _get_store()
    namespace = _get_namespace()
    
    col_str = ", ".join(columns)
    dtype_str = ", ".join([f"{k} ({v})" for k, v in schema.items()])
    
    memory_text = (
        f"Timestamp: {_get_timestamp()}, "
        f"Memory Type: {MEMORY_TYPE_DATASET_SUMMARY}, "
        f"Dataset loaded: {file_name}, "
        f"Columns available: \"{col_str}\", "
        f"Schema/Data Types: \"{dtype_str}\""
    )
    
    value = {
        MEMORY_KEY: memory_text,
        "memory_type": MEMORY_TYPE_DATASET_SUMMARY,
        "file_name": file_name
    }
    
    store.put(namespace, "dataset_summary", value)

def summarize_exchange(user_prompt: str, ai_code: str, output_type: str) -> tuple[str, str]:
    """
    Creates a concise, ~50 token summary of the exchange to be used as a searchable memory.

    Args:
        user_prompt: The user's question (prompt).
        ai_code: The code generated by the AI.
        output_type: The result type (table/figure) produced by AI's code.
    """
    # Format the context directly. Truncate long code / output_type str to save context & embedding dims.
    trunc_code = ai_code.strip()[:200]
    if len(ai_code.strip()) > 200: trunc_code += "..."
        
    trunc_output = str(output_type).strip()[:200]
    if len(str(output_type).strip()) > 200: trunc_output += "..."
    memory_ts = _get_timestamp()
    
    memory_text = (
        f"Timestamp: {memory_ts}, "
        f"Memory Type: {MEMORY_TYPE_PRIOR_PROMPT}, "
        f"User prompt: {user_prompt}, "
        f"Agent response (SUMMARY of code): \"{trunc_code}\", "
        f"Result Type: {trunc_output}"
    )
    return memory_text, memory_ts

def store_exchange(user_prompt: str, ai_code: str, output_type: str) -> None:
    """
    Summarizes and stores a user-assistant exchange into the memory store.

    Args:
        user_prompt: The user's question (prompt).
        ai_code: The code generated by the AI.
        output_type: The result type (table/figure) produced by AI's code.
    """
    store = _get_store()
    namespace = _get_namespace()
    
    memory_text, memory_ts = summarize_exchange(user_prompt, ai_code, output_type)
    value = {
        MEMORY_KEY: memory_text,
        MEMORY_TS: memory_ts,
        "memory_type": f"{MEMORY_TYPE_PRIOR_PROMPT}.",
        USER_PROMPT: user_prompt,
        AGENT_CODE: ai_code,
        "output_type": output_type
    }
    
    # Use a unique key for each exchange
    key = str(uuid_lib.uuid4())
    store.put(namespace, key, value)

def _get_relevant_memories(query: str, limit: int = 1000) -> list:
    """
    Retrieves the raw memory items from the store based on the user's new query.
    Returns memories ranked by similarity. May include 
    memories that are not relevant to the query (fillers).

    Args:
        query: The user's query.
        limit: The maximum number of memories to retrieve from the underlying store.

    Returns:
        List of language graph SearchItem objects containing scores and values.
    """
    store = _get_store()
    namespace = _get_namespace()

    # Embeds query via the index configuration & performs cosine similarity against all items
    similar_items = store.search(namespace, query=query, limit=limit)
    all_items = store.search(namespace, filter={})
    log.info(f"Current Memory Store Size: {len(all_items)}")
    log.info(f"Current Similar Items (from raw search): {len(similar_items)}")

    return similar_items

def get_relevant_memories(query: str, limit: int = 5, trim_threshold: int = 5, score_threshold: float = 0.52) -> List[Dict[str, Any]]:
    """
    Retrieves the most semantically relevant memories from the store based on the user's new query.
    Enforces a strict distance/similarity threshold to ignore filler memories.

    Args:
        query: The user's query.
        limit: The maximum number of memories to retrieve.
        score_threshold: The minimum cosine similarity score required (0.0 to 1.0) to be considered relevant.

    Returns:
        List of dict - for easy prompt construction 
    """
    _trim_namespace(trim_threshold)
    # Get all results first (pass a very large limit)
    raw_items = _get_relevant_memories(query, limit=1000)
    
    valid_items = []
    for item in raw_items:
        # Check if the item has an explicit embedded similarity score
        score = getattr(item, 'score', 0.0)
        
        # Keep items above the semantic similarity threshold
        if score and score >= score_threshold:
            valid_items.append(item)
            log.debug(f"Relevant memory kept: {item}\nSemantic similarity score: {score}")

    # Order the memories by MEMORY_TS (most recent first) and then rank by score (highest first).
    # Python sort is stable, so sort by a tuple: (score, timestamp) descending
    valid_items.sort(key=lambda x: (getattr(x, 'score', 0.0), x.value.get(MEMORY_TS, "")), reverse=True)
    
    # Apply requested limit
    limited_items = valid_items[:limit]
    
    return [item.value for item in limited_items]

def _trim_namespace(max_memories: int, ts_key: str = MEMORY_TS):
    
    store = _get_store()
    namespace = _get_namespace()
    items = store.search(namespace, filter={}) 

    if len(items) <= max_memories:
        return

    # sort asc
    items_sorted = sorted(
        items,
        key=lambda it: it.value.get(ts_key, ""),
    )
    num_to_delete = len(items_sorted) - max_memories
    log.debug(f"Staging trim of: {num_to_delete} memories from namespace {namespace}")
    to_delete = items_sorted[:num_to_delete]

    for mem_item in to_delete:
        store.delete(namespace, mem_item.key)

def get_dataset_summary() -> Dict[str, Any]:
    """
    Retrieves the dataset summary from the memory store.

    Returns:
        Dict[str, Any] - The dataset summary.
    """
    store = _get_store()
    namespace = _get_namespace()
    
    item = store.get(namespace, MEMORY_TYPE_DATASET_SUMMARY)
    return item.value if item else None 