from dataclasses import dataclass, field
from typing import Any, List, Dict, Optional
import streamlit as st
import pydc.util.constants as constants

@dataclass
class PydcSessionWrapper:
    """
    Wrapper around st.session_state for PyData Copilot. 
    The dataclass handles creating __init__.
    
    This class provides a convenient way to access and manage the session state
    of the PyData Copilot application. It allows for easy access to the
    dataframe, file name, messages, and other session-specific attributes.
    
    Attributes:
        df (Any): The dataframe containing the data to be analyzed.
        file_name (Optional[str]): The name of the file that was uploaded.
        messages (List[Any]): The list of messages in the chat history.
        has_asked_question (bool): Whether the user has asked a question.
        generated_code (str): The code that was generated by the AI.
        show_code (bool): Whether to show the generated code.
        dataset_handler (Any): The dataset handler for the current dataset.
        df_row_slider (int): The number of rows to display in the dataframe.
        user_avatar (str): The avatar for the user.
        assistant_avatar (str): The avatar for the assistant.
        python_logo (str): The logo for Python.
        _state (Any): The underlying Streamlit session_state dict.
    """

    # Core attributes required in PyData Copilot session state
    df: Any = None
    file_name: Optional[str] = None
    messages: List[Any] = field(default_factory=list)
    has_asked_question: bool = False
    generated_code: str = ""
    show_code: bool = False
    dataset_handler: Any = None
    df_row_slider: int = constants.ROW_SLIDER_DEFAULT
    result_type: str = ""
    table: Any = None
    figure: Any = None  
    errors: Dict[str, Any] = field(default_factory=dict)
    user_avatar: str = constants.IMAGE_LKP["user_avatar"]
    assistant_avatar: str = constants.IMAGE_LKP["assistant_avatar"]
    python_logo: str = constants.IMAGE_LKP["python_logo"]

    # Reference to the underlying session_state dict
    _state: Any = field(default_factory=lambda: st.session_state, repr=False)

    
    def __post_init__(self):
        # initialize from existing session_state when created
        for key, value in self._state.items():
            if not key.startswith("_"):
                super().__setattr__(key, value)
    
    def __setattr__(self, name: str, value: Any) -> None:
        """
        Any assignment like pydc.some_attr = value will:
            - update the dataclass field
        - update st.session_state['some_attr'] as well
        """
        super().__setattr__(name, value)
        
        # 1. Protects against updating session state if _state hasn't been setup yet
        # (which happens during the dataclass's own __init__ phase).
        # 2. Skip updating st.session_state for private attributes (startswith "_").
        if not name.startswith("_") and hasattr(self, "_state"):
            self._state[name] = value
    
    
    @classmethod
    def from_session(cls) -> "PydcSessionWrapper":
        return cls(_state=st.session_state)
    
    
    def set(self, key: str, value: Any) -> None:
        """Create or update a dynamic attribute and session_state key."""
        setattr(self, key, value)  # will go through __setattr__

    def reset(self, dataset_handler: Any = None) -> None:
        """
        Reset all known fields to their default values.
        This will also overwrite the corresponding keys in st.session_state.
        """
        self._state.clear()
        if dataset_handler is not None:
            self.dataset_handler = dataset_handler
            self.df = dataset_handler.df
            self.file_name = dataset_handler.file_name
        else:
            self.dataset_handler = None
            self.df = None
            self.file_name = None
        
        self.messages = []
        self.has_asked_question = False
        self.generated_code = ""
        self.show_code = False
        self.df_row_slider = constants.ROW_SLIDER_DEFAULT
        self.result_type = ""
        self.table = None
        self.figure = None
        self.errors = {}
        self.user_avatar = constants.IMAGE_LKP["user_avatar"]
        self.assistant_avatar = constants.IMAGE_LKP["assistant_avatar"]
        self.python_logo = constants.IMAGE_LKP["python_logo"]
        
        
 
   